version: '3.4'

services:
  AbreuRocha.Codeflix.Catalog:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Codeflix@123
      
networks: 
  default:
    name: service_catalog